### ISSUE TITLE
Inability to access dashboard/diagnostics during blockchain outage

### ISSUE THREAD

**Issue by shrtcut** [NebraLtd/helium-miner-software#233] opened 2021-11-18 10:51 UTC
**Describe the bug**
No local dashboard/diagnostics tool access when blockchain has issues. Am I allowed to suggest that the local dashboard should always be accessible even if the blockchain has issues? (peace of mind for user(s)?)

**To Reproduce**
1. Go to local IP.....Internal Server 500 error even though blockchain is up. (ish)

**Expected behavior**
Local IP/Dashboard should always be accessible even without connectivity to external servers.

**Additional context**
I understand the blockchain has had issues recently, however not having access to the local diagnostics page whilst we have big outages seems a bit counterintuitive.

Could this just be an effect of multiple firmware upgrades during this period and as a result the dashboard/diag page has been put on backburner?

**Comment by shawaj** [comment] 2021-11-18 12:27
Duplicate of #223

**Closed by shawaj** 2021-11-18 12:27 UTC
