### ISSUE TITLE
Onboarding Error and no connecting via Bluetooth

### ISSUE THREAD

**Issue by JohnFilz** [NebraLtd/helium-miner-software#858] opened 2023-08-04 05:38 UTC
Onboarding Error and no connecting via Bluetooth 

Hello guys,

I am new here and also still with the topic of helium mining.
Unfortunately I am not getting anywhere with the setup. The hotspot does not want to connect to the Helium network and I do not understand why.
I already wrote to the support but didn't really get a solution.
I have created screenshots to show you what I mean exactly.
You are my hope to solve the problem.

I am very grateful for any helpful tips.

![image](https://github.com/NebraLtd/helium-syncrobit/assets/140860379/1ac22a6d-00b7-47b1-8182-f65edf8b06c6)
![image](https://github.com/NebraLtd/helium-syncrobit/assets/140860379/fdebcea8-fbb2-49ac-ba5b-eb16acaa7e2b)
![image](https://github.com/NebraLtd/helium-syncrobit/assets/140860379/7e504e09-792f-406a-945d-7b6d8106960f)
![image](https://github.com/NebraLtd/helium-syncrobit/assets/140860379/068cb78c-4c65-4ac1-b6fa-2212d9dc736b)
![image](https://github.com/NebraLtd/helium-syncrobit/assets/140860379/847f6d88-c39a-40f5-ad54-b3b5372768d0)
![image](https://github.com/NebraLtd/helium-syncrobit/assets/140860379/ed63c0dc-d31c-4e8f-82f4-2371cea4a2aa)
![image](https://github.com/NebraLtd/helium-syncrobit/assets/140860379/8171757b-c86a-440c-89bd-e774f1b86fd1)
![image](https://github.com/NebraLtd/helium-syncrobit/assets/140860379/9d7202d2-74a6-4176-8edf-2d3bebbbaf27)

_Originally posted by @JohnFilz in https://github.com/NebraLtd/helium-syncrobit/issues/3#issuecomment-1664934325_

**Comment by shawaj** [comment] 2023-08-04 16:04
Closing as this is a support issue not a bug

**Comment by shawaj** [comment] 2023-08-04 16:04
Ticket [#430847](https://nebra.freshdesk.com/a/tickets/430847) for Nebra Use

**Closed by shawaj** 2023-08-04 16:04 UTC
