### ISSUE TITLE
Investigate potential to pass helium animal name back to balenaCloud

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-miner-software#63] opened 2021-05-31 17:05 UTC
Investigate potential to pass the Helium animal name back to balenaCloud...

**Comment by ryanteck** [comment] 2021-06-03 11:05
Duplicate of https://github.com/NebraLtd/helium-miner-software/issues/58

**Closed by ryanteck** 2021-06-03 11:05 UTC

**Comment by shawaj** [comment] 2021-06-05 14:44
oops sorry! my bad
