### ISSUE TITLE
Factory reset

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/helium-miner-software#85] opened 2021-07-02 08:55 UTC
We need to document the process of performing factory resets for customers.

**Comment by vpetersson** [comment] 2021-07-02 08:56
Some internal documents:
https://docs.google.com/document/d/1xwxqqucas9h7RqTfKgFC4Vo_jiIorAWFmx39zB-BBDI/edit

**Comment by ganey** [comment] 2021-07-02 10:23
While you're at it, is there a process for a customer controlling their own hostspot image? Could we update GA's by ourselves?

It may not be on your immediate timeline, but i've just had a load of 4 year old smart plugs go dark because the remote server has gone. Luckily I can re-flash the firmware and control them locally over MQTT/REST.

**Comment by vpetersson** [comment] 2021-07-02 10:26
Thanks @ganey. Not clear how this will be done at this point as the system is tightly integrated with Balena. It would in theory be possible in the future to take over control.

**Comment by ganey** [comment] 2021-07-02 10:32
Ah okay thanks. 

Do the hotspots run BalenaOS as the host then? If so, it probably wouldn't be too difficult to move devices to self-hosted openBalena if someone **really** wanted to (at their own risk of course).

**Comment by vpetersson** [comment] 2021-07-02 10:35
Correct. All miners are running balenaOS, and all code that runs on them is open sourced (to my knowledge).

**Comment by shawaj** [comment] 2021-07-02 17:37
Yes they run balenaOS. You could either use openbalena or use balenaCloud as I think first 10 devices are free.

You could do it now and just reflash your device and push our repo to the application. But obviously then you'd be responsible for pushing the updates yourself.

**Comment by ganey** [comment] 2021-07-02 17:51
Thank you both for clarifying, I have no plans to do this in the short term, but it's great to know it's possible.

**Comment by shawaj** [comment] 2021-07-02 19:49
Actually @ganey we are also in discussions with balena to see whether we can support our devices and other manufacturers as well on balena openfleets. But not got a huge amount of time to sort that ATM

**Comment by shawaj** [comment] 2021-07-02 19:52
FYI @vpetersson below is from balena about how we can allow customers to flash there devices and still have it on our fleet, with a single use image...

Each time a customer needs to reflash their CM3 due to booting issues, what you can do is pre-register a new device in the balena CLI which will create a new device in your application and generate a random UUID. The crucial step here is to then create a configuration file that includes this new UUID, which is then injected into a downloaded image from your application.    

Once the customer has flashed their device with the OS image you have provided, they won't be able to duplicate the SD card to other devices, as the UUID in the configuration file in the OS image will have already been used.   

So in practise this would work as follows:   
1. Customer complains of booting issues that would require a reflash   
2. Nebra preregisters new device  >balena device register YOURAPP --uuid 6053dab8dc4721ed288c8dfc79052967     
3. Nebra creates new config file  > $ balena config generate --app cliApp --version 2.38.0+rev1 --device 6053dab8dc4721ed288c8dfc79052967 --network ethernet --appUpdatePollInterval 10 --output config.json   
4. Nebra injects config into OS image  $ balena os configure Nebra-HNT.img --config config.json --device 6053dab8dc4721ed288c8dfc79052967   
5. Nebra supply OS image to customer for flashing.   

You can read through the full guide on how to do this here:  https://github.com/balena-io/balena-cli-advanced-masterclass#52-preregistering-a-device

**Comment by devicefckdup** [comment] 2021-08-16 11:20
Hello there...

I was wondering if you could perform factory resets on two of my NEBRA indoor hotspots? I cant do it myself since I am unable to approach your official NEBRA dashboard...the bug in question is "the device does not exist". Ive tryed a dozen times, scanned the codes over and over again, manually entered codes...but none of my hotspots is recognized by your dashboard software. I ve already submitted a ticket to nebra support email, but no answer has been given. Both of my hotspots suddenly stopped all activity, without any logical reason...and they are dead for weeks now. They previously worked fine, my internet connection is top of the line, ports are open, the devices are backed up with colling units, everything should be in order...except it isnt, and my units arent mining at all. I ve manually unplugged and plugged them numerous time...it didnt helped, restarted the routers...didnt helped. Ergo...I am here, asking you for your help and guidance. 
I can provide you with additional information...MAC codes, ETH code and all that, just tell me where to approach you...since nebra support email doesnt give me any feedback for weeks now.

**Comment by Premmmi** [comment] 2021-08-23 16:34
Hi, 
I have the same problem as @devicefckdup
Can you help me?

**Comment by vpetersson** [comment] 2021-08-23 16:35
This is not for end-user support. This is for software bugs. @Premmmi / @devicefckdup please reach out to support@nebra.com

**Comment by icep87** [comment] 2021-09-22 06:05
Any updates on this? It would be good to have the instructions now that the support is so overwhelmed. 
The file that was shared in the second comment is not public.

**Comment by vpetersson** [comment] 2021-09-22 07:48
This can only be done by support. It's not possible to do by end-users.

**Comment by icep87** [comment] 2021-09-22 08:57
Okey, thank you for a response. Will have to wait for the support to get back to me.

**Comment by icep87** [comment] 2021-09-29 19:56
Can something be wrong with the eMMC module if the device is not booting up properly as the green led never turns on. But the device is syncing with the blockchain and diagnostic does not show that anything is wrong. I've received this hotspot 3 weeks ago and has not been able to onboard it since. Support is not responding, I have ticket 279266 that they stopped to respond too. Can the eMMC be wiped so everything is downloaded again?

**Comment by dowjames** [comment] 2021-10-06 04:20
I'd be interested in this too, since I have a miner that is stuck on Miner Is Still Loading.

**Comment by shawaj** [comment] 2021-11-05 04:11
@KevinWassermann94 I think we have documented this internally now so guess we can close this issue?

**Comment by Ryan-Goldstein** [comment] 2021-11-05 04:27
Can you tell us how to factory reset then if you have it documented internally? There are tons of people with a Nebra where the external green LED isn't illuminating, they can't be paired with Bluetooth and thus can't be onboarded, and support hasn't responded despite the tickets being opened for many weeks (see my support ticket 287423).

I received my Nebra on October 19, it's now November 5, and it's still just sitting here unable to be onboarded despite extensive troubleshooting efforts. Full details [here](https://www.reddit.com/r/HeliumNetwork/comments/qds6ol/nebra_firmware_issues_cannot_onboard/).

**Comment by shawaj** [comment] 2021-11-05 04:45
@Ryan-Goldstein it's not possible for anyone but Nebra staff to do this I'm afraid

**Comment by shawaj** [comment] 2021-11-05 05:01
@Ryan-Goldstein p.s. had a quick look at your hotspot and it seems something on the ECC has gone wrong. This is a very rare issue and unlikely to be an issue caused by the updates. 

In any case please leave the hotspot on and connected to internet and we will attempt a remote fix

**Comment by Ryan-Goldstein** [comment] 2021-11-05 05:02
@shawaj Will do, I'll keep it online, thanks for taking a look!

**Comment by JohnMaguire** [comment] 2021-11-05 05:18
> @Ryan-Goldstein p.s. had a quick look at your hotspot and it seems something on the ECC has gone wrong. This is a very rare issue and unlikely (impossible) to be an issue caused by the updates.
> 
> In any case please leave the hotspot on and connected to internet and we will attempt a remote fix

Hi @shawaj - is it possible that this is the same issue affecting the rest of us on https://github.com/NebraLtd/helium-miner-software/issues/175?

**Comment by shawaj** [comment] 2021-11-05 05:32
@JohnMaguire almost certainly not but hard to say really. Best thing is to email support@nebra.com

**Comment by icep87** [comment] 2021-11-05 05:46
@JohnMaguire Email them, but I've been waiting for a response regarding the ECC for 3 months now. I copied my friend EEC card and move over the config file from my non properly working eMMC to the SD card to have it running right now.

**Comment by KevinWassermann94** [comment] 2021-11-05 11:36
@shawaj Yes this can be closed. We have the internal document for it

**Closed** 2021-11-05 18:54 UTC

**Comment by Ryan-Goldstein** [comment] 2021-11-09 17:42
> @Ryan-Goldstein p.s. had a quick look at your hotspot and it seems something on the ECC has gone wrong. This is a very rare issue and unlikely (impossible) to be an issue caused by the updates.
> 
> In any case please leave the hotspot on and connected to internet and we will attempt a remote fix

@shawaj I've kept my Nebra online, and I received an email from support on 5 November requesting photos of the inside of my hotspot, which I immediately sent, sent a follow-up yesterday, but I haven't heard anything since. My hotspot (eth 00:BD:27:00:1D:A1) is still in the same state.

Any chance you can try to get this fixed? I've had this hotspot that I haven't been able to onboard since receiving it on 19 October, 3 weeks ago. Thanks.
