### ISSUE TITLE
Make Logs Available on Diagnostics Page

### ISSUE THREAD

**Issue by tesarm** [NebraLtd/helium-miner-software#116] opened 2021-08-18 12:56 UTC
My miner randomly goes down. It's still connected and responding to ping on the network, but I can't access any of the ports - not responding to 80 / 44158 

It would be really useful to have logs accessible so we can investigate what's happening. 

Maybe we could add a link to the diagnostics page and include last xxx lines from each log file?

**Comment by KevinWassermann94** [comment] 2021-08-18 12:57
Please send us a mail to sales@nebra.com and we will investigate on the issue

**Comment by tesarm** [comment] 2021-08-18 13:00
> Please send us a mail to [sales@nebra.com](mailto:sales@nebra.com) and we will investigate on the issue

I've done that few days ago, I had no response so I wanted to see if I could possibly diagnose what's happening

**Comment by shawaj** [comment] 2021-08-18 14:52
Duplicate of https://github.com/NebraLtd/hm-diag/issues/51

**Closed by shawaj** 2021-08-18 14:52 UTC
